import React, { useEffect, useRef, useState } from 'react';
import { Check, Film, Upload, Play, ShieldCheck, GitBranch, Download, RefreshCw, AlertTriangle, ArrowRight, LogOut } from 'lucide-react';
import { request, setToken, download } from './client';
import './studio.css';

export default function Studio() {
  const [signedIn,setSignedIn]=useState(false), [key,setKey]=useState('');
  const [projects,setProjects]=useState<any[]>([]), [project,setProject]=useState<any>(null);
  const [tab,setTab]=useState('intake'), [busy,setBusy]=useState(''), [error,setError]=useState('');
  const [title,setTitle]=useState(''), [script,setScript]=useState('');
  const [locale,setLocale]=useState('es-419'), [kind,setKind]=useState('SUBTITLE'), [parent,setParent]=useState(''), [offset,setOffset]=useState('0');
  const [selected,setSelected]=useState<string[]>([]), [specText,setSpecText]=useState(''), [editing,setEditing]=useState<string|null>(null), [proposalText,setProposalText]=useState('');
  const [evidenceId,setEvidenceId]=useState<string|null>(null), [playTime,setPlayTime]=useState(0);
  const [videoUrl,setVideoUrl]=useState(''); const video=useRef<HTMLVideoElement>(null);
  const ppath=project ? `/projects/${project.id}` : '';
  async function run(label:string,fn:()=>Promise<void>) { setBusy(label);setError('');try{await fn();}catch(e:any){setError(e.message);if(project){try{setProject(await request(ppath));}catch{}}}finally{setBusy('');} }
  async function refresh() { setProjects(await request('/projects')); }
  async function update(action:string,body:any={}) { const next=await request(ppath+action,'POST',{revision:project.revision,...body});setProject(next);setSelected([]);await refresh(); }
  useEffect(()=>{setSpecText(project?.spec?JSON.stringify(project.spec,null,2):'');},[project?.revision]);
  useEffect(()=>{let url='';setVideoUrl('');if(project?.media_key)download(`/projects/${project.id}/media`).then(blob=>{url=URL.createObjectURL(blob);setVideoUrl(url);}).catch(()=>{});return()=>{if(url)URL.revokeObjectURL(url);};},[project?.media_key]);
  async function signIn(e:React.FormEvent){e.preventDefault();await run('Signing in',async()=>{setToken(key);await request('/session');setSignedIn(true);setKey('');await refresh();});}
  async function upload(file:File|undefined,media=false){if(!file)return;await run('Uploading',async()=>{const form=new FormData();form.append('file',file);form.append('revision',String(project.revision));if(!media){form.append('locale',locale);form.append('kind',kind);form.append('parent_id',parent);form.append('master_offset',offset);}setProject(await request(ppath+(media?'/media':'/assets'),'POST',form));await refresh();});}
  const assetName=(id:string)=>project?.assets.find((a:any)=>a.id===id)?.name||id;
  const evidenceFinding=project?.findings.find((f:any)=>f.id===evidenceId)||project?.findings[0];
  const evidenceAsset=project?.assets.find((a:any)=>a.id===evidenceFinding?.asset_id);
  const activeCue=evidenceAsset?.cues.find((c:any)=>playTime>=(c.start+evidenceAsset.master_offset)&&playTime<(c.end+evidenceAsset.master_offset));
  const signout=()=>{setToken('');setSignedIn(false);setProject(null);setProjects([]);};
  if(!signedIn)return <main className="login"><div className="login-art"><Film size={38}/><span className="eyebrow">STORYPARITY / REVIEW STUDIO</span><h1>Every audience.<br/>The same story.</h1><p>Find where meaning, timing or accessibility changed between your master and its localized versions.</p><div className="login-flow">MASTER <ArrowRight size={16}/> VERSIONS <ArrowRight size={16}/> VERIFIED DELIVERY</div></div><form onSubmit={signIn} className="login-form"><span className="eyebrow">PRIVATE REVIEW WORKSPACE</span><h2>Enter the studio</h2><p>Use your reviewer access key to open projects and authorize changes.</p><label>Reviewer access key<input type="password" autoComplete="off" required minLength={24} value={key} onChange={e=>setKey(e.target.value)}/></label>{error&&<p role="alert" className="error">{error}</p>}<button disabled={!!busy}>{busy||'Open workspace'} <ArrowRight size={17}/></button><small>Your key stays in memory for this session.</small></form></main>;
  return <div className="studio"><aside><div className="brand"><Film/> StoryParity</div><span className="eyebrow">REVIEW WORKSPACE</span><button className="new-project secondary" onClick={()=>{setProject(null);setTab('intake');}}>+ New project</button><nav>{projects.map(p=><button key={p.id} className={project?.id===p.id?'active':''} onClick={()=>run('Opening project',async()=>{setProject(await request(`/projects/${p.id}`));setSelected([]);setTab('intake');})}><Film size={16}/><span>{p.title}<small>{p.status.replaceAll('_',' ').toLowerCase()}</small></span></button>)}</nav><div className="aside-bottom"><ShieldCheck size={17}/> Human approval required<button className="quiet" onClick={signout}><LogOut size={14}/> Sign out</button></div></aside><main><header><div><span className="eyebrow">LOCALIZATION & ACCESSIBILITY INTEGRITY</span><h1>{project?.title||'Start with your master'}</h1></div>{project&&<div className="header-actions"><span className={'status '+(project.status==='VERIFIED'?'good':'')}>{project.status.replaceAll('_',' ')}</span><button className="secondary" disabled={!!busy} onClick={()=>run('Exporting',async()=>{const blob=await download(ppath+'/export');const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`storyparity-${project.id}.zip`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);})}><Download size={16}/> Export</button></div>}</header>
  {error&&<div role="alert" className="error banner"><AlertTriangle size={18}/>{error}<button className="quiet" onClick={()=>setError('')}>Dismiss</button></div>}{busy&&<div role="status" className="busy"><RefreshCw className="spin" size={16}/>{busy}…</div>}
  {!project?<section className="panel create"><span className="eyebrow">01 / INGEST</span><h2>One master. Every version.</h2><p>Create a project, then upload the master clip and downstream tracks.</p><form onSubmit={e=>{e.preventDefault();run('Creating project',async()=>{setProject(await request('/projects','POST',{title,script}));await refresh();});}}><label>Project title<input required maxLength={150} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Protocol Kepler-9"/></label><label>Approved master script<textarea required maxLength={100000} rows={10} value={script} onChange={e=>setScript(e.target.value)} placeholder="Include dialogue and clip-relative timing where available."/></label><button disabled={!!busy}>Create project <ArrowRight size={16}/></button></form></section>:<><div className="tabs">{[['intake','01','Sources'],['spec','02','Story specification'],['findings','03','Findings'],['review','04','Repairs'],['trace','05','Activity']].map(([id,n,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><span>{n}</span>{label}</button>)}</div>
  {tab==='intake'&&<><div className="grid"><section className="panel"><span className="eyebrow">APPROVED SOURCE</span><h2>Master clip</h2>{videoUrl?<video ref={video} controls src={videoUrl}/>:<div className="media-placeholder"><Film size={40}/><p>Upload a short master scene</p><small>MP4, WebM, WAV or MP3 · up to 20 MB</small></div>}<label className="file-button"><Upload size={15}/> {project.media_key?'Replace master':'Upload master'}<input type="file" accept="video/mp4,video/webm,audio/wav,audio/mpeg" disabled={!!busy} onChange={e=>upload(e.target.files?.[0],true)}/></label><details><summary>Master script</summary><pre>{project.script}</pre></details></section><section className="panel"><span className="eyebrow">DOWNSTREAM VERSIONS</span><h2>Add a track</h2><div className="form-row"><label>Locale<input value={locale} onChange={e=>setLocale(e.target.value)} maxLength={20}/></label><label>Track type<select value={kind} onChange={e=>setKind(e.target.value)}>{['SUBTITLE','SDH','DUB','AD'].map(k=><option key={k}>{k}</option>)}</select></label></div><label>Derived from<select value={parent} onChange={e=>setParent(e.target.value)}><option value="">Master / independent version</option>{project.assets.map((a:any)=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Master timeline offset (seconds)<input type="number" step="0.01" value={offset} onChange={e=>setOffset(e.target.value)}/><small>Master time = track time + offset. Use 0 for aligned tracks.</small></label><label className="file-button"><Upload size={15}/> Upload SRT, VTT or JSON<input type="file" accept=".srt,.vtt,.json" disabled={!!busy} onChange={e=>upload(e.target.files?.[0])}/></label><p className="muted">JSON cue arrays support normalized placement boxes for on-screen clue checks.</p></section></div><section className="panel"><div className="section-heading"><h2>Version inventory <span className="count">{project.assets.length}</span></h2><button disabled={!!busy} onClick={()=>run('Extracting story specification with Gemini',async()=>{await update('/extract');setTab('spec');})}>Extract story specification <ArrowRight size={16}/></button></div><table><thead><tr><th>Asset</th><th>Locale</th><th>Type</th><th>Cues</th><th>Revision</th></tr></thead><tbody>{project.assets.map((a:any)=><tr key={a.id}><td>{a.parent_id&&<GitBranch size={13}/>} {a.name}</td><td>{a.locale}</td><td>{a.kind}</td><td>{a.cues.length}</td><td>v{a.revision}</td></tr>)}</tbody></table>{!project.assets.length&&<p className="empty">No downstream tracks yet.</p>}</section></>}
  {tab==='spec'&&<section className="panel"><div className="section-heading"><div><span className="eyebrow">HUMAN-REVIEWED SOURCE OF TRUTH</span><h2>Story specification</h2></div><button disabled={!!busy} onClick={()=>run('Extracting with Gemini',()=>update('/extract'))}><RefreshCw size={15}/> Extract again</button></div><p>Check each fact against the master. Times use the clip timeline; boxes use coordinates from 0 to 1. Edit the structured specification before approving it.</p>{project.spec?<><div className="invariant-grid">{project.spec.invariants.map((i:any)=><article key={i.id}><span className="tag">{i.kind}</span><strong>{i.description}</strong><span>{i.start.toFixed(2)}–{i.end.toFixed(2)}s · {i.value}</span><blockquote>{i.evidence}</blockquote></article>)}</div><details><summary>Edit structured specification</summary><textarea className="code" rows={18} value={specText} onChange={e=>setSpecText(e.target.value)}/><button className="secondary" disabled={!!busy} onClick={()=>run('Saving specification',async()=>setProject(await request(ppath+'/spec','PUT',{revision:project.revision,spec:JSON.parse(specText)})))}>Save edits</button></details><div className="actions"><button disabled={!!busy||project.approved_spec_digest===project.spec_digest} onClick={()=>run('Approving specification',()=>update('/spec/approve',{digest:project.spec_digest}))}><ShieldCheck size={16}/>{project.approved_spec_digest===project.spec_digest?'Specification approved':'Approve this specification'}</button><button className="secondary" disabled={!!busy||!project.approved_spec_digest||!project.assets.length} onClick={()=>run('Indexing and checking through ClickHouse MCP',async()=>{await update('/scan');setTab('findings');})}>Run parity checks <ArrowRight size={16}/></button></div></>:<p className="empty">Extract a specification from the master to begin review.</p>}</section>}
  {tab==='findings'&&<><section className="panel section-heading"><div><span className="eyebrow">EVIDENCE BEFORE ACTION</span><h2>{project.findings.length} findings to review</h2><p>Semantic matches are review candidates. Timing and placement checks use approved intervals and regions.</p></div><div className="actions"><button className="secondary" disabled={!!busy} onClick={()=>run('Rechecking current versions',()=>update('/scan'))}><RefreshCw size={15}/> Recheck</button><button disabled={!!busy||!selected.length} onClick={()=>run('Agent investigating selected findings',async()=>{await update('/investigate',{finding_ids:selected});setTab('review');})}>Investigate {selected.length||''} selected</button></div></section>{videoUrl&&<section className="panel evidence-player"><div className="evidence-video"><video ref={video} controls src={videoUrl} onTimeUpdate={e=>setPlayTime(e.currentTarget.currentTime)}/>{activeCue&&<div className="cue-overlay" style={activeCue.box?{left:`${activeCue.box.x*100}%`,top:`${activeCue.box.y*100}%`,width:`${activeCue.box.width*100}%`,height:`${activeCue.box.height*100}%`}:undefined}>{activeCue.text}</div>}</div><div><span className="eyebrow">TIMECODE-LINKED EVIDENCE</span><h3>{evidenceAsset?.name||'Master clip'}</h3><p>{evidenceFinding?.description}</p><blockquote>{evidenceFinding?.evidence}</blockquote><small>Master: {playTime.toFixed(2)}s · track offset: {evidenceAsset?.master_offset||0}s. Overlay previews supplied cue text and placement.</small><button className="secondary" disabled={!evidenceFinding} onClick={()=>{if(video.current&&evidenceFinding){video.current.currentTime=Math.max(0,evidenceFinding.start+(evidenceAsset?.master_offset||0));video.current.play().catch(()=>{});}}}><Play size={15}/> Play this moment</button></div></section>}<div className="findings-grid">{project.findings.map((f:any)=><article className="panel finding" key={f.id}><div className="section-heading"><span className="tag warn">{f.kind} · {f.severity}</span><input aria-label={`Select ${f.description}`} type="checkbox" checked={selected.includes(f.id)} onChange={e=>setSelected(e.target.checked?[...selected,f.id]:selected.filter(x=>x!==f.id))}/></div><h3>{f.description}</h3><p>{assetName(f.asset_id)} · cue {f.cue_id||'missing'}</p><blockquote>{f.evidence}</blockquote><span className="time">{f.start.toFixed(2)}–{f.end.toFixed(2)}s</span><button className="quiet" onClick={()=>{setEvidenceId(f.id);if(video.current){video.current.currentTime=Math.max(0,f.start+(project.assets.find((a:any)=>a.id===f.asset_id)?.master_offset||0));}}}><Play size={13}/> Review evidence</button></article>)}</div>{!project.findings.length&&<section className="panel empty"><Check size={28}/><h2>{project.status==='VERIFIED'?'Current checks passed':'No current findings'}</h2><p>{project.status==='VERIFIED'?'Download the versioned delivery report for evidence and scope.':'Approve the specification and run a scan to generate findings.'}</p></section>}</>}
  {tab==='review'&&<><div className="section-heading"><div><span className="eyebrow">YOU CONTROL EVERY CHANGE</span><h2>Repair proposals</h2></div></div>{project.proposals.slice().reverse().map((p:any)=><section className="panel proposal" key={p.id}><div className="section-heading"><h3>{p.rationale}</h3><span className="tag">{p.status}</span></div>{p.uncertainty&&<p className="muted">Review note: {p.uncertainty}</p>}{p.changes.map((c:any,i:number)=>{const original=project.assets.find((a:any)=>a.id===c.asset_id)?.cues.find((q:any)=>q.id===c.cue_id);return <div className="change" key={i}><strong>{assetName(c.asset_id)} · cue {c.cue_id} · {c.operation}</strong><div className="diff"><pre className="before">{original?.text||'(missing cue)'}</pre><pre className="after">{c.replacement?.text||'(delete cue)'}{c.replacement&&`\n${c.replacement.start.toFixed(2)}–${c.replacement.end.toFixed(2)}s`}{c.replacement?.box&&`\nPlacement: ${JSON.stringify(c.replacement.box)}`}</pre></div></div>})}{editing===p.id&&<><textarea className="code" rows={16} value={proposalText} onChange={e=>setProposalText(e.target.value)}/><button onClick={()=>run('Saving reviewed proposal',async()=>{setProject(await request(ppath+`/proposals/${p.id}`,'PUT',{revision:project.revision,proposal:JSON.parse(proposalText)}));setEditing(null);})}>Save edits</button></>}<div className="actions">{p.status==='PROPOSED'?<><button disabled={!!busy} onClick={()=>run('Applying approved changes and verifying',()=>update(`/proposals/${p.id}/apply`,{digest:p.approval_digest}))}><ShieldCheck size={16}/> Approve exact changes & verify</button><button className="secondary" disabled={!!busy} onClick={()=>{setEditing(p.id);const copy={...p};delete copy.approval_digest;setProposalText(JSON.stringify(copy,null,2));}}>Edit proposal</button><button className="quiet" disabled={!!busy} onClick={()=>run('Rejecting proposal',()=>update(`/proposals/${p.id}/reject`))}>Reject</button></>:p.status==='APPLIED'&&<button className="secondary" disabled={!!busy} onClick={()=>run('Rolling back and rechecking',()=>update(`/proposals/${p.id}/rollback`))}>Roll back these changes</button>}</div><small className="hash">Review fingerprint: {p.approval_digest}</small></section>)}{!project.proposals.length&&<section className="panel empty"><ShieldCheck size={30}/><h2>No proposed changes yet</h2><p>Select findings and run an investigation. Nothing is applied without your approval.</p></section>}</>}
  {tab==='trace'&&<section className="panel"><span className="eyebrow">PERSISTED WORKFLOW HISTORY</span><h2>Activity & tool evidence</h2><div className="timeline">{project.events.slice().reverse().map((e:any,i:number)=><article key={i}><span className="timeline-dot"/><div><strong>{e.action.replaceAll('_',' ')}</strong><small>{new Date(e.at).toLocaleString()} · {e.actor}</small><details><summary>View evidence</summary><pre>{JSON.stringify(e.details,null,2)}</pre></details></div></article>)}</div></section>}
  </>}<footer>StoryParity · Every audience gets the same story.<span>AI investigates. People approve. Checks verify.</span></footer></main></div>;
}
