import React, { useEffect, useRef, useState } from 'react';
import { Check, Film, Upload, Play, ShieldCheck, GitBranch, Download, RefreshCw, AlertTriangle, ArrowRight, LogOut } from 'lucide-react';
import { request, setToken, download } from './client';
import './studio.css';
import {ChangePreview, ChangeEditor, VersionImpact} from './ReviewTools';

export default function Studio() {
  const [signedIn,setSignedIn]=useState(false), [key,setKey]=useState('');
  const [projects,setProjects]=useState<any[]>([]), [project,setProject]=useState<any>(null);
  const [tab,setTab]=useState('intake'), [busy,setBusy]=useState(''), [error,setError]=useState('');
  const [title,setTitle]=useState(''), [script,setScript]=useState('');
  const [locale,setLanguage]=useState('es-419'), [kind,setKind]=useState('SUBTITLE'), [parent,setParent]=useState(''), [offset,setOffset]=useState('0');
  const [selected,setSelected]=useState<string[]>([]), [specText,setSpecText]=useState(''), [editing,setEditing]=useState<string|null>(null), [proposalText,setProposalText]=useState('');
  const [evidenceId,setEvidenceId]=useState<string|null>(null), [playTime,setPlayTime]=useState(0);
  const [videoUrl,setVideoUrl]=useState(''); const video=useRef<HTMLVideoElement>(null);
  const ppath=project ? `/projects/${project.id}` : '';
  async function run(label:string,fn:()=>Promise<void>) { setBusy(label);setError('');try{await fn();}catch(e:any){setError(e.message);if(project){try{setProject(await request(ppath));}catch{}}}finally{setBusy('');} }
  async function refresh() { setProjects(await request('/projects')); }
  async function update(action:string,body:any={}) { const next=await request(ppath+action,'POST',{revision:project.revision,...body});setProject(next);setSelected([]);await refresh(); }
  useEffect(()=>{setSpecText(project?.spec?JSON.stringify(project.spec,null,2):'');},[project?.revision]);
  useEffect(()=>{let url='';setVideoUrl('');if(project?.media_key)download(`/projects/${project.id}/media`).then(blob=>{url=URL.createObjectURL(blob);setVideoUrl(url);}).catch(()=>{});return()=>{if(url)URL.revokeObjectURL(url);};},[project?.media_key]);
  async function signIn(e:React.FormEvent){e.preventDefault();await run('Signing in',async()=>{setToken(key);await request('/session');setSignedIn(true);setKey('');await refresh();});}
  async function upload(file:File|undefined,media=false){if(!file)return;await run('Uploading',async()=>{const form=new FormData();form.append('file',file);form.append('revision',String(project.revision));if(!media){form.append('locale',locale);form.append('kind',kind);form.append('parent_id',parent);form.append('master_offset',offset);}setProject(await request(ppath+(media?'/media':'/assets'),'POST',form));await refresh();});}
  const trackLabels:Record<string,string>={SUBTITLE:'Subtitles',SDH:'Accessible captions',DUB:'Dub transcript',AD:'Audio description'};
  const statusLabel=(value:string)=>({INGESTED:'Getting started',READY_FOR_SCAN:'Ready to check',MASTER_CHANGED:'Review the updated film',FINDINGS_OPEN:'Needs review',PROPOSAL_REVIEW:'Changes to review',VERIFIED:'Ready',VERIFICATION_PENDING:'Check needed',PROPOSED:'For review',APPLIED:'Applied',ROLLED_BACK:'Undone',REJECTED:'Rejected'}[value]||value.replace(/_/g,' ').toLowerCase());
  const issueLabels:Record<string,string>={NUMBER:'Numbers',REVEAL:'Reveals',SOUND:'Captions',DIALOGUE:'Audio description',CLUE:'On-screen text'};
  const findingTitle=(f:any)=>({REVEAL:'An identity is revealed too early',SOUND:'A key sound may be missing',DIALOGUE:'Audio description overlaps dialogue',CLUE:'A subtitle covers an on-screen clue'}[f.kind]||f.description.replace('Expected numeric fact','Expected').replace(/\. Confirm.*$/,''));
  const assetName=(id:string)=>project?.assets.find((a:any)=>a.id===id)?.name||id;
  const evidenceFinding=project?.findings.find((f:any)=>f.id===evidenceId)||project?.findings[0];
  const evidenceAsset=project?.assets.find((a:any)=>a.id===evidenceFinding?.asset_id);
  const activeCue=evidenceAsset?.cues.find((c:any)=>playTime>=(c.start+evidenceAsset.master_offset)&&playTime<(c.end+evidenceAsset.master_offset));
  const signout=()=>{setToken('');setSignedIn(false);setProject(null);setProjects([]);};
  if(!signedIn)return <main className="login"><div className="login-art"><Film size={38}/><h1>Accord</h1><p>Keep the story intact across every version.</p></div><form onSubmit={signIn} className="login-form"><h2>Welcome back</h2><label>Access code<input type="password" autoComplete="off" required minLength={24} value={key} onChange={e=>setKey(e.target.value)}/></label>{error&&<p role="alert" className="error">{error}</p>}<button disabled={!!busy}>{busy||'Continue'} <ArrowRight size={17}/></button></form></main>;
  return <div className="studio"><aside><div className="brand"><Film/> Accord</div><button className="new-project secondary" onClick={()=>{setProject(null);setTab('intake');}}>+ New project</button><nav>{projects.map(p=><button key={p.id} className={project?.id===p.id?'active':''} onClick={()=>run('Opening project',async()=>{setProject(await request(`/projects/${p.id}`));setSelected([]);setTab('intake');})}><Film size={16}/><span>{p.title}<small>{statusLabel(p.status)}</small></span></button>)}</nav><div className="aside-bottom"><button className="quiet" onClick={signout}><LogOut size={14}/> Sign out</button></div></aside><main><header><div><h1>{project?.title||'Your projects'}</h1></div>{project&&<div className="header-actions"><span className={'status '+(project.status==='VERIFIED'?'good':'')}>{statusLabel(project.status)}</span><button className="secondary" disabled={!!busy} onClick={()=>run('Exporting',async()=>{const blob=await download(ppath+'/export');const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`accord-${project.id}.zip`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);})}><Download size={16}/> Export</button></div>}</header>
  {error&&<div role="alert" className="error banner"><AlertTriangle size={18}/>{error}<button className="quiet" onClick={()=>setError('')}>Dismiss</button></div>}{busy&&<div role="status" className="busy"><RefreshCw className="spin" size={16}/>{busy}…</div>}
  {!project?<section className="panel create"><h2>Create a project</h2><p>Add your original film and the versions you want to review.</p><form onSubmit={e=>{e.preventDefault();run('Creating project',async()=>{setProject(await request('/projects','POST',{title,script}));await refresh();});}}><label>Project title<input required maxLength={150} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Protocol Kepler-9"/></label><label>Original script<textarea required maxLength={100000} rows={10} value={script} onChange={e=>setScript(e.target.value)} placeholder="Add the dialogue and any important scene notes."/></label><button disabled={!!busy}>Create project <ArrowRight size={16}/></button></form></section>:<><div className="tabs">{[['intake','01','Sources'],['spec','02','Story notes'],['findings','03','Review'],['review','04','Changes'],['trace','05','History']].map(([id,n,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {tab==='intake'&&<><div className="grid"><section className="panel"><h2>Original film</h2>{videoUrl?<video ref={video} controls src={videoUrl}/>:<div className="media-placeholder"><Film size={40}/><p>Add your original film</p><small>MP4, WebM, WAV or MP3 · up to 20 MB</small></div>}<label className="file-button"><Upload size={15}/> {project.media_key?'Replace film':'Upload film'}<input type="file" accept="video/mp4,video/webm,audio/wav,audio/mpeg" disabled={!!busy} onChange={e=>upload(e.target.files?.[0],true)}/></label><details><summary>Original script</summary><pre>{project.script}</pre></details></section><section className="panel"><h2>Add a track</h2><div className="form-row"><label>Language<input value={locale} onChange={e=>setLanguage(e.target.value)} maxLength={20}/></label><label>Track type<select value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(trackLabels).map(([k,label])=><option key={k} value={k}>{label}</option>)}</select></label></div><details><summary>Timing and linked versions</summary><label>Derived from<select value={parent} onChange={e=>setParent(e.target.value)}><option value="">Original film</option>{project.assets.map((a:any)=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Starts in the original film at (seconds)<input type="number" step="0.01" value={offset} onChange={e=>setOffset(e.target.value)}/><small>Leave at 0 when both versions start at the same point.</small></label></details><label className="file-button"><Upload size={15}/> Upload SRT, VTT or JSON<input type="file" accept=".srt,.vtt,.json" disabled={!!busy} onChange={e=>upload(e.target.files?.[0])}/></label></section></div><section className="panel"><div className="section-heading"><h2>Your versions <span className="count">{project.assets.length}</span></h2><button disabled={!!busy} onClick={()=>run('Reading your film',async()=>{await update('/extract');setTab('spec');})}>Create story notes <ArrowRight size={16}/></button></div><table><thead><tr><th>Asset</th><th>Language</th><th>Type</th><th>Cues</th><th>Revision</th></tr></thead><tbody>{project.assets.map((a:any)=><tr key={a.id}><td>{a.parent_id&&<GitBranch size={13}/>} {a.name}</td><td>{a.locale}</td><td>{trackLabels[a.kind]||a.kind}</td><td>{a.cues.length}</td><td>v{a.revision}</td></tr>)}</tbody></table>{!project.assets.length&&<p className="empty">Add a version to begin.</p>}</section></>}
  {tab==='intake'&&<VersionImpact assets={project.assets} findings={project.findings}/>}
  {tab==='spec'&&<section className="panel"><div className="section-heading"><div><h2>Story notes</h2></div><button disabled={!!busy} onClick={()=>run('Reading your film',()=>update('/extract'))}><RefreshCw size={15}/> Refresh notes</button></div><p>Review these details against your film, then approve them to check your versions.</p>{project.spec?<><div className="invariant-grid">{project.spec.invariants.map((i:any)=><article key={i.id}><span className="tag">{issueLabels[i.kind]||i.kind}</span><strong>{i.description}</strong><span>{i.start.toFixed(2)}–{i.end.toFixed(2)}s · {i.value}</span><blockquote>{i.evidence}</blockquote></article>)}</div><details><summary>Advanced: edit story notes</summary><textarea className="code" rows={18} value={specText} onChange={e=>setSpecText(e.target.value)}/><button className="secondary" disabled={!!busy} onClick={()=>run('Saving notes',async()=>setProject(await request(ppath+'/spec','PUT',{revision:project.revision,spec:JSON.parse(specText)})))}>Save edits</button></details><div className="actions"><button disabled={!!busy||project.approved_spec_digest===project.spec_digest} onClick={()=>run('Approving notes',()=>update('/spec/approve',{digest:project.spec_digest}))}><ShieldCheck size={16}/>{project.approved_spec_digest===project.spec_digest?'Notes approved':'Approve story notes'}</button><button className="secondary" disabled={!!busy||!project.approved_spec_digest||!project.assets.length} onClick={()=>run('Checking your versions',async()=>{await update('/scan');setTab('findings');})}>Check versions <ArrowRight size={16}/></button></div></>:<p className="empty">Create story notes from your film to begin.</p>}</section>}
  {tab==='findings'&&<><section className="panel section-heading"><div><h2>{project.findings.length} findings to review</h2><p>Choose the issues you want to work on.</p></div><div className="actions"><button className="secondary" disabled={!!busy} onClick={()=>run('Rechecking current versions',()=>update('/scan'))}><RefreshCw size={15}/> Recheck</button><button disabled={!!busy||!selected.length} onClick={()=>run('Preparing suggested changes',async()=>{await update('/investigate',{finding_ids:selected});setTab('review');})}>Suggest changes {selected.length ? `(${selected.length})` : ''}</button></div></section>{videoUrl&&<section className="panel evidence-player"><div className="evidence-video"><video ref={video} controls src={videoUrl} onTimeUpdate={e=>setPlayTime(e.currentTarget.currentTime)}/>{activeCue&&<div className="cue-overlay" style={activeCue.box?{left:`${activeCue.box.x*100}%`,top:`${activeCue.box.y*100}%`,width:`${activeCue.box.width*100}%`,height:`${activeCue.box.height*100}%`}:undefined}>{activeCue.text}</div>}</div><div><h3>{evidenceAsset?.name||'Original film'}</h3><p>{evidenceFinding&&findingTitle(evidenceFinding)}</p><blockquote>{evidenceFinding?.evidence}</blockquote><small>{playTime.toFixed(2)}s</small><button className="secondary" disabled={!evidenceFinding} onClick={()=>{if(video.current&&evidenceFinding){video.current.currentTime=Math.max(0,evidenceFinding.start+(evidenceAsset?.master_offset||0));video.current.play().catch(()=>{});}}}><Play size={15}/> Play this moment</button></div></section>}<div className="findings-grid">{project.findings.map((f:any)=><article className="panel finding" key={f.id}><div className="section-heading"><span className="tag warn">{issueLabels[f.kind]||f.kind}</span><input aria-label={`Select ${f.description}`} type="checkbox" checked={selected.includes(f.id)} onChange={e=>setSelected(e.target.checked?[...selected,f.id]:selected.filter(x=>x!==f.id))}/></div><h3>{findingTitle(f)}</h3><p>{assetName(f.asset_id)} · cue {f.cue_id||'missing'}</p><blockquote>{f.evidence}</blockquote><span className="time">{f.start.toFixed(2)}–{f.end.toFixed(2)}s</span><button className="quiet" onClick={()=>{setEvidenceId(f.id);if(video.current){video.current.currentTime=Math.max(0,f.start+(project.assets.find((a:any)=>a.id===f.asset_id)?.master_offset||0));}}}><Play size={13}/> Review evidence</button></article>)}</div>{!project.findings.length&&<section className="panel empty"><Check size={28}/><h2>{project.status==='VERIFIED'?'Ready to download':'Nothing to review yet'}</h2><p>{project.status==='VERIFIED'?'Your versions passed the checks. Download them when you’re ready.':'Approve your story notes, then check your versions.'}</p></section>}</>}
  {tab==='review'&&<><div className="section-heading"><div><h2>Suggested changes</h2></div></div>{project.proposals.slice().reverse().map((p:any)=><section className="panel proposal" key={p.id}><div className="section-heading"><h3>{p.rationale}</h3><span className="tag">{statusLabel(p.status)}</span></div>{p.uncertainty&&<p className="muted">Review note: {p.uncertainty}</p>}{videoUrl&&['PROPOSED','APPLIED'].includes(p.status)&&<ChangePreview assets={project.assets} proposal={{...p,preview_assets:project.proposal_previews?.[p.id]}} videoUrl={videoUrl}/>}{p.changes.map((c:any,i:number)=>{const original=(p.status==='APPLIED'?project.proposal_previews?.[p.id]:project.assets)?.find((a:any)=>a.id===c.asset_id)?.cues.find((q:any)=>q.id===c.cue_id);return <div className="change" key={i}><strong>{assetName(c.asset_id)} · cue {c.cue_id} · {{REPLACE:'Update',INSERT:'Add',DELETE:'Remove'}[c.operation]}</strong><div className="diff"><pre className="before">{original?.text||'(missing cue)'}</pre><pre className="after">{c.replacement?.text||'(delete cue)'}{c.replacement&&`\n${c.replacement.start.toFixed(2)}–${c.replacement.end.toFixed(2)}s`}{c.replacement?.box&&`\nPosition: ${Math.round(c.replacement.box.x*100)}% from left, ${Math.round(c.replacement.box.y*100)}% from top`}</pre></div></div>})}<VersionImpact assets={project.assets} findings={project.findings} changes={p.status==='PROPOSED'?p.changes:[]}/>{editing===p.id&&<ChangeEditor proposal={p} assets={project.assets} busy={!!busy} onCancel={()=>setEditing(null)} onSave={async draft=>{await run('Saving reviewed changes',async()=>{const copy={...draft};delete copy.approval_digest;setProject(await request(ppath+`/proposals/${p.id}`,'PUT',{revision:project.revision,proposal:copy}));setEditing(null);await refresh();});}}/>}<div className="actions">{p.status==='PROPOSED'?<><button disabled={!!busy||editing!==null} onClick={()=>run('Applying and checking your changes',()=>update(`/proposals/${p.id}/apply`,{digest:p.approval_digest}))}><ShieldCheck size={16}/> Approve and apply</button><button className="secondary" disabled={!!busy} onClick={()=>{setEditing(p.id);const copy={...p};delete copy.approval_digest;setProposalText(JSON.stringify(copy,null,2));}}>Edit changes</button><button className="quiet" disabled={!!busy} onClick={()=>run('Rejecting changes',()=>update(`/proposals/${p.id}/reject`))}>Reject</button></>:p.status==='APPLIED'&&<button className="secondary" disabled={!!busy} onClick={()=>run('Restoring previous versions',()=>update(`/proposals/${p.id}/rollback`))}>Undo these changes</button>}</div></section>)}{!project.proposals.length&&<section className="panel empty"><ShieldCheck size={30}/><h2>No proposed changes yet</h2><p>Select an issue in Review to get suggestions. You choose which changes to apply.</p></section>}</>}
  {tab==='trace'&&<section className="panel"><h2>Project history</h2><div className="timeline">{project.events.slice().reverse().map((e:any,i:number)=><article key={i}><span className="timeline-dot"/><div><strong>{e.action.replaceAll('_',' ')}</strong><small>{new Date(e.at).toLocaleString()} · {e.actor}</small><details><summary>Technical details</summary><pre>{JSON.stringify(e.details,null,2)}</pre></details></div></article>)}</div></section>}
  </>}</main></div>;
}
